service: express-api-v2

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: prod
  timeout: 30
  memorySize: 1024
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:CreateBucket
            - s3:GetObject
            - s3:DeleteObject            
          Resource: arn:aws:s3:::curoo-uploads-profile/*
        
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:AssignPrivateIpAddresses
            - ec2:UnassignPrivateIpAddresses
          Resource: "*"
  vpc:
    securityGroupIds:
      - sg-040d555d266a4d63a
    subnetIds:
      - subnet-0787bc44d5a29d2a6
      - subnet-0ed14d2f9005a4169      

  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    MJ_APIKEY_PUBLIC: ${env:MJ_APIKEY_PUBLIC}
    MJ_APIKEY_PRIVATE: ${env:MJ_APIKEY_PRIVATE}
    MAILJET_FROM_EMAIL: ${env:MAILJET_FROM_EMAIL}
    VITE_BASE_URL: ${env:VITE_BASE_URL}
    JWT_EXPIRATION: ${env:JWT_EXPIRATION}    
    CONSULT_EXPIRE_HOURS: ${env:CONSULT_EXPIRE_HOURS}
    UPLOADS_BUCKET: curoo-uploads-profile
    SES_ACCESS_KEY_ID: ${env:SES_ACCESS_KEY_ID}
    SES_SECRET_ACCESS_KEY: ${env:SES_SECRET_ACCESS_KEY}
    SES_FROM_EMAIL: ${env:SES_FROM_EMAIL}

functions:
  api:
    handler: src/server.handler
    timeout: 25
    events:
      - httpApi:
          path: /api/{proxy+}
          method: ANY   

  hourlyCron:
    handler: src/cron/handler.handler
    timeout: 60
    events:
      - eventBridge:
          schedule: cron(0 * * * ? *)

plugins:
  - serverless-esbuild  

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node18
    platform: node
    concurrency: 1  
    format: cjs
    outputFileExtension: .js
    external:
      - aws-sdk
    exclude:
      - aws-sdk                    
